version: "2"

services:
    tasker:
        image: strm/tasker
        volumes:
            - "./src/main/resources/application.yml:/application.yml"
            - "/var/run/docker.sock:/var/run/docker.sock"
