logging:
  level:
    ROOT: DEBUG
    
schedule:
  - every: 1 minutes
    task: hello
    name: testEveryMinute
    
tasks:
  docker:
    - name: hello
      image: debian:jessie
      script:
        - echo Hello world from Tasker
        
